root: true # ignore config in main folder

extends:
  - airbnb/base
  - prettier

env:
  node: true
  mocha: true

plugins:
  - prettier

rules:
  prettier/prettier: ["error", {"trailingComma": "es5", "singleQuote": true}]
  semi: ["error", "always"]
  global-require: 0
