sudo: false
language: node_js

env:
  - NODE_ENV=development

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 6
  - 8
  - 10

before_install:
  - npm i -g codeclimate-test-reporter

script:
  - npm run test || travis_terminate 1
  - codeclimate-test-reporter < ./coverage/lcov.info
  - npm run coveralls

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: 8
      env: NODE_ENV=production
      before_install: skip
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

addons:
  code_climate:
    repo_token: c2f5565ff4d312c27c2864e45d361d9767f9f6cba820bd705b422ca75f69c706
