sudo: false
language: node_js
env:
  - NODE_ENV=development
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - 8
  - 6
  - 10
before_install:
  - npm -v
  - npm i -g codeclimate-test-reporter
script:
  - npm run test
after_success:
  - nvm install 8
  - nvm use 8
  - codeclimate-test-reporter < ./coverage/lcov.info
  - npm run coveralls
  - semantic-release
addons:
  code_climate:
    repo_token: c2f5565ff4d312c27c2864e45d361d9767f9f6cba820bd705b422ca75f69c706
