language: node_js
node_js:
  - "14.17.3"
cache:
  directories:
    - ".meteor"
    - ".babel-cache"
script:
  - export TEST_PACKAGES_EXCLUDE="less"
  - export phantom=false
  # to skip Downloading Chromium on every run
  # https://github.com/dfernandez79/puppeteer/blob/main/README.md#q-chromium-gets-downloaded-on-every-npm-ci-run-how-can-i-cache-the-download
  - export PUPPETEER_DOWNLOAD_PATH=~/.npm/chromium
  - travis_retry ./packages/test-in-console/run.sh
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
