name: Meteor Docs version
on:
  push:
    paths:
      - 'docs/**/*'
    branches:
      - 'version-**'
jobs:
  deploy-versioned:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs/
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Build the Docs
        run: npm ci && npm run build
      - name: Get version
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo "BRANCH=$branch" >> $GITHUB_ENV
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2.2
        with:
          publish-dir: './docs/public'
          production-branch: devel
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: Deploy from GitHub Actions devel
          netlify-config-path: './docs/netlify.toml'
          enable-pull-request-comment: false
          enable-commit-comment: false
          alias: ${{ env.BRANCH }}
          github-deployment-environment: 'branch'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DOCS_SITE_ID }}
